using System.Collections.Generic;
using SharpAstrology.Enums;

namespace HDKitSample
{
    public static class GateInfo
    {
        public static readonly Dictionary<Gates, string> Descriptions = new()
        {
            { Gates.Key1, "Self-expression, creative self; the energy to initiate unique contribution." },
            { Gates.Key2, "Direction of the self; the receptive guide for direction and resources." },
            { Gates.Key3, "Ordering and mutation; difficulty at the beginning leading to innovation." },
            { Gates.Key4, "Formulation of answers; mental solutions and logical structuring." },
            { Gates.Key5, "Fixed patterns; rhythm and consistency in life." },
            { Gates.Key6, "Friction in relationships; emotional boundaries and intimacy." },
            { Gates.Key7, "Leadership of the collective; role-model guidance and direction." },
            { Gates.Key8, "Contribution to the collective; style and articulation of unique contribution." },
            { Gates.Key9, "Focus; attention to detail and small, consistent effort." },
            { Gates.Key10, "Behavior of the self; natural self-love and authenticity." },
            { Gates.Key11, "Ideas; the creative mind and conceptualization." },
            { Gates.Key12, "Caution in expression; spoken expression that can attract or repel." },
            { Gates.Key13, "The listener; storytelling and collective memory." },
            { Gates.Key14, "Power skills; role in providing resources and value." },
            { Gates.Key15, "Extremes and humanity; rhythm and acceptance of diversity." },
            { Gates.Key16, "Skills and enthusiasm; talent and practiced mastery." },
            { Gates.Key17, "Opinions and logical formulation; patterns of thought." },
            { Gates.Key18, "Correction; critique to improve systems and form." },
            { Gates.Key19, "Sensitivity and needs; the voice of community need and close ties." },
            { Gates.Key20, "Now consciousness; presence and immediate expression." },
            { Gates.Key21, "Control and management; resources and regulation." },
            { Gates.Key22, "Openness and charm; mood and social grace." },
            { Gates.Key23, "Assimilation of ideas; simplicity and transformation of complex thought." },
            { Gates.Key24, "Rationalization; returning to insight after mental processing." },
            { Gates.Key25, "Innocence and spirit; universal love and acceptance." },
            { Gates.Key26, "Integrity of persuasion; salesmanship and ego integrity." },
            { Gates.Key27, "Caring and nourishment; responsibility for others' wellbeing." },
            { Gates.Key28, "Struggle and purpose; confronting risk to find meaning." },
            { Gates.Key29, "Commitment; perseverance through trial and repetition." },
            { Gates.Key30, "Intensity of feelings; desire and emotional experience." },
            { Gates.Key31, "Leadership through influence; democratic voice and leadership." },
            { Gates.Key32, "Continuity; preservation and business acumen." },
            { Gates.Key33, "Privacy and retreat; reflection and storytelling." },
            { Gates.Key34, "Power and charisma; pure empowering energy in action." },
            { Gates.Key35, "Change and experience; cycles of progress and new experiences." },
            { Gates.Key36, "Crisis and emotional depth; exploration of feeling experiences." },
            { Gates.Key37, "Community and friendship; family and group cooperation." },
            { Gates.Key38, "Opposition and struggle; finding meaning through challenge." },
            { Gates.Key39, "Provocation and stimulation; initiating emotional reactions." },
            { Gates.Key40, "Aloneness and deliverance; rest and work balance." },
            { Gates.Key41, "Contraction and imagination; beginnings and fantasy." },
            { Gates.Key42, "Growth cycles; completion and maturation processes." },
            { Gates.Key43, "Insight and uniqueness; breakthrough ideas and alienation." },
            { Gates.Key44, "Alertness to patterns; historical instinct and team dynamics." },
            { Gates.Key45, "Gathering and rulership; distribution of resources and leadership." },
            { Gates.Key46, "Determination of the body; serendipity and embodied success." },
            { Gates.Key47, "Realization and mental processing; resolving confusion into insight." },
            { Gates.Key48, "Depth and resource; talent and need for correction and skill." },
            { Gates.Key49, "Principles and revolution; values leading to social change." },
            { Gates.Key50, "Values and preservation; caring for traditions and community." },
            { Gates.Key51, "Shock and initiation; arousal and awakening forces." },
            { Gates.Key52, "Stillness and concentrated focus; restraint and meditation." },
            { Gates.Key53, "Beginnings and cycles; initiation of incremental journeys." },
            { Gates.Key54, "Ambition and drive; converting resources into status and growth." },
            { Gates.Key55, "Spirit and abundance; emotional fullness and existential mood." },
            { Gates.Key56, "Stimulation through story; wandering mind and storytelling." },
            { Gates.Key57, "Intuition and clarity; instinctive foresight and sensitivity." },
            { Gates.Key58, "Joy and vitality; corrective energy toward wellbeing." },
            { Gates.Key59, "Intimacy and bonding; sexual connection and breaking barriers." },
            { Gates.Key60, "Limitation and acceptance; mutation within constraints." },
            { Gates.Key61, "Inner truth and mystery; inspiration and philosophical insight." },
            { Gates.Key62, "Detail and articulation; precise expression and organization." },
            { Gates.Key63, "Doubt and questioning; critical inquiry and verification." },
            { Gates.Key64, "Confusion to abstraction; mental pressure to sense patterns." },
        };
    }
}
